#include "BIT_MATH.h"
#include "STD_TYPES.h"
#include "WatchDog_private.h"
#include "WatchDog_config.h"
#include "WatchDog_interface.h"


void WDT_vidInit()
{
	SET_BIT(WDTCR,WDTOE);
	#if PRE_SCALE==TIME1
	CLR_BIT(WDTCR,WDP2);
	CLR_BIT(WDTCR,WDP1);
	CLR_BIT(WDTCR,WDP0);
	#elif PRE_SCALE==TIME2
	SET_BIT(WDTCR,WDP2);
	CLR_BIT(WDTCR,WDP1);
	CLR_BIT(WDTCR,WDP0);
	#elif PRE_SCALE==TIME3
	CLR_BIT(WDTCR,WDP2);
	SET_BIT(WDTCR,WDP1);
	CLR_BIT(WDTCR,WDP0);
	#elif PRE_SCALE==TIME4
	SET_BIT(WDTCR,WDP2);
	SET_BIT(WDTCR,WDP1);
	CLR_BIT(WDTCR,WDP0);
	#elif PRE_SCALE==TIME5
	CLR_BIT(WDTCR,WDP2);
	CLR_BIT(WDTCR,WDP1);
	SET_BIT(WDTCR,WDP0);
	#elif PRE_SCALE==TIME6
	SET_BIT(WDTCR,WDP2);
	CLR_BIT(WDTCR,WDP1);
	SET_BIT(WDTCR,WDP0);
	#elif PRE_SCALE==TIME7
	CLR_BIT(WDTCR,WDP2);
	CLR_BIT(WDTCR,WDP1);
	SET_BIT(WDTCR,WDP0);
	#elif PRE_SCALE==TIME8
	SET_BIT(WDTCR,WDP2);
	SET_BIT(WDTCR,WDP1);
	SET_BIT(WDTCR,WDP0);
	#endif
}
void WDT_vidEnableWDT()
{
	SET_BIT(WDTCR,WDE);
}
void WDT_vidDisableWDT()
{
	WDTCR=0x18;
	CLR_BIT(WDTCR,WDE);
	
}
